### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by aManNamedJed** [drud/ddevcom#140]
# Testing Plan

- [x] Verify that the testing plan located at docs/test-plan.md of the repository is up to date and accurate.
- [x] Release plan is documented
- [ ] Verify that code is tagged with appropriate version - blocked by #171 
- [ ] Verify that all tests pass on all supported browsers and devices

Work in progress

## **Main Navigation**

[Staging](https://preview-ddev-staging-ddev-external-sites.sites.ddev.live/) | [Production](https://ddev.com/)

- [x] Click **DDEV Logo** and confirm it navigates to the home page
- [x] Click **Products -> DDEV-Live** and confirm it navigates to the DDEV-Live product page
- [x] Click **Products -> DDEV-Local**  and confirm it navigates to the DDEV-Local product page
- [x] Click **Developers -> Documentation -> DDEV-Local Docs** and confirm it navigates to the [DDEV-Local documentation](https://ddev.readthedocs.io/en/stable) in a new tab
- [x] Click **Developers -> Documentation -> DDEV-Live Docs** and confirm it navigates to the [DDEV-Live documentation ](https://docs.ddev.com) in a new tab
- [x] Click **Developers -> Documentation -> GitHub** and confirm it navigates to the [Drud GitHub](https://github.com/drud) in a new tab
- [x] Click **Developers -> Documentation -> Jobs** and confirm it navigates to the Jobs page
- [x] Click **Events** and confirm it navigates to the Events page. 
- [x] Click **Blog** and confirm it navigates to the Blog page
- [x] Click **Contact** and confirm it navigates to the Contact page

## Front Page

[Staging](https://preview-ddev-staging-ddev-external-sites.sites.ddev.live/) | [Production](https://ddev.com/)

- [x] Click **Deploy to our cloud** button and confirm it navigates to the DDEV-Live product page
- [x] Click **Develop locally** button and confirm it navigates to the DDEV-Local product page
- [x] Confirm the Recent Posts section is displaying the most recent six posts.
- [x] Click the **Join Newsletter** button and confirm it navigates to our Mailchimp newsletter signup form.  [Should open in new tab, issue here. Tested, Passed and Closed 06/01](https://github.com/drud/ddevcom/issues/151)
## DDEV-Live Page

[Staging](https://preview-ddev-staging-ddev-external-sites.sites.ddev.live/ddev-live) | [Production](https://ddev.com/ddev-live)

### Navigation

- [x] Click **Start a free trial** and confirm it navigates to the DDEV-Live dashboard registration page.  [Should open in a new tab, issue here.  Tested, Passed 06/01](https://github.com/drud/ddevcom/issues/153)
- [x] Click **Pricing** and confirm it navigates to the DDEV-Live dashboard pricing page.  [Should open in a new tab, issue here.  Tested, Passed 06/01](https://github.com/drud/ddevcom/issues/154)
- [x] Click **Developers -> Documentation** and confirm it navigates to the DDEV-Live documentation in a new tab
- [x] Click **Developers -> Get Started** and confirm it navigates to the Get Started section of the DDEV-Live documentation in a new tab

### Main Hero

- [x] Click **Start a free trial** button and confirm it navigates to the DDEV-Live dashboard registration page.  [Should open in a new tab, see issue 153.  Tested, Passed 06/01](https://github.com/drud/ddevcom/issues/153)
- [x] Click **Documentation** button and confirm it navigates to the DDEV-Live documentation in a new tab.

### Features

- [x] Click **Git Integration -> Git repository provider** link and confirm it navigates to the DDEV-Live Providers documentation in a new tab
- [x] Click **Continuous Integration -> CI/CD** link and confirm it navigates to the DDEV-Live CI/CD page
- [x] Click **Tutorial: DDEV-LIve + Jenkins** button and confirm it navigates to the DDEV-Live Jenkins tutorial documentation.  [Should open in a new tab, issue here.  Tested, Passed 06/01](https://github.com/drud/ddevcom/issues/155)
- [x] Click the next **Start a free trial** button and confirm it navigates to the DDEV-Live dashboard registration page.  [Should open in a new tab, see issue 153. Tested, Passed 06/01](https://github.com/drud/ddevcom/issues/153)
- [x] Click the next **Request Demo** button and confirm it navigates to the Contact page
- [x] Click the final **Start a free trial** button and confirm it navigates to the DDEV-Live dashboard registration page. [ Should open in a new tab, see issue 153.  Tested, Passed 06/01](https://github.com/drud/ddevcom/issues/153)
- [x] Click the final **Request Demo** button and confirm it navigates to the Contact page

### Recent Posts

- [x] Verify the **Recent Posts** section only displays the most recent posts with DDEV Live category.  [Missing a Recent Post header, posts are for DDEV Local not Live. Tested, Passed 06/01](https://github.com/drud/ddevcom/issues/156)
- [x] Check the blog cards using the **Blog Posts** checklist below
- [x] Verify the **Join Newsletter** button links to our Mailchimp form in a new tab

## DDEV-Local Page

[Staging](https://preview-ddev-staging-ddev-external-sites.sites.ddev.live/ddev-local) | [Production](https://ddev.com/ddev-local)

### Navigation

- [x] Click **Get Started** and confirm it navigates to the Get Started page
- [x] Click **Documentation** and confirm it navigates to the DDEV-Local documentation in a new tab
- [x] Click **Quickstart Guides -> PHP** and confirm it navigates to the DDEV-Local documentation quickstart guide for PHP in a new tab
- [x] Click **Quickstart Guides -> WordPress** and confirm it navigates to the DDEV-Local documentation quickstart guide for WordPress in a new tab
- [x] Click **Quickstart Guides -> Drupal 8** and confirm it navigates to the DDEV-Local documentation quickstart guide for Drupal 8 in a new tab
- [x] Click **Quickstart Guides -> Drupal 9** and confirm it navigates to the DDEV-Local documentation quickstart guide for Drupal 9 in a new tab
- [x] Click **Quickstart Guides -> Drupal 6 & 7** and confirm it navigates to the DDEV-Local documentation quickstart guide for Drupal 6 & 7 in a new tab
- [x] Click **Quickstart Guides -> TYPO3** and confirm it navigates to the DDEV-Local documentation quickstart guide for TYPO3 in a new tab
- [x] Click **Quickstart Guides -> Backdrop** and confirm it navigates to the DDEV-Local documentation quickstart guide for Backdrop in a new tab
- [x] Click **Quickstart Guides -> Magento 1** and confirm it navigates to the DDEV-Local documentation quickstart guide for Magento 1 in a new tab
- [x] Click **Quickstart Guides -> Magento 2** and confirm it navigates to the DDEV-Local documentation quickstart guide for Magento 2 in a new tab
- [x] Click **GitHub** and confirm it navigates to the DDEV-Local GitHub page in a new tab
- [x] Click **Get Started** and confirm it navigates to the Get Started page
- [x] Click **Documentation** and confirm it navigates to the Documentation in a new tab

### Features

- [x] Click **Get Started** and confirm it navigates to the Get Started page
- [x] Click **Documentation** and confirm it navigates to the Documentation in a new tab
- [x] Click the next **Get Started** and confirm it navigates to the Get Started page
- [x] Click the next **Documentation** and confirm it navigates to the Documentation in a new tab

### Recent Posts

- [x] Verify the **Recent Posts** section only displays the most recent posts with DDEV Local category.  Blocked by #157. Tested, Passed, Closed 06/01
- [x] Check the blog cards using the **Blog Posts** checklist below
- [x] Verify the **Join Newsletter** button links to our Mailchimp form in a new tab

## Blog Posts

- [x] Click a blog card's image and confirm it goes to that blog post
- [x] Click a blog card's title and confirm it goes to that blog post
- [x] Click a blog card's author and confirm it goes to that author's post archive. Blocked by #158.  Tested, Passed 06/01
