### ISSUE TITLE
Add Twitter and LinkedIn tracking code to ddev.com

### ISSUE THREAD

**Issue by ekl1773** [drud/ddevcom#203]
## Feature Description:
Add tracking code from Twitter and LinkedIn to ddev.com so WideFocus can get more data from visitors.

### Twitter
"You just need to place the attached code at the bottom of all pages on your website before the </body> HTML tag."

```
<!-- Twitter universal website tag code -->
<script>
!function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);
},s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js',
a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
// Insert Twitter Pixel ID and Standard Event data below
twq('init','nzpya');
twq('track','PageView');
</script>
<!-- End Twitter universal website tag code -->
```

### LinkedIn

> The LinkedIn Insight Tag is a lightweight Javascript snippet that drops a cookie on visitors' web browsers whenever they visit the site. This will allow you to track whenever a member converts on your website.

> 1.
> First, copy the code:
> ```<script type="text/javascript"> _linkedin_partner_id = "2605052"; window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || []; window._linkedin_data_partner_ids.push(_linkedin_partner_id); </script><script type="text/javascript"> (function(){var s = document.getElementsByTagName("script")[0]; var b = document.createElement("script"); b.type = "text/javascript";b.async = true; b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js"; s.parentNode.insertBefore(b, s);})(); </script> <noscript> <img height="1" width="1" style="display:none;" alt="" src="https://px.ads.linkedin.com/collect/?pid=2605052&fmt=gif" /> </noscript>```

> 2.
> Next, paste the code into the global footer of your domain either before or after the `<body>` tag.
> Finally, log in to the [LinkedIn Campaign Manager](https://www.linkedin.com/campaignmanager/) and navigate to the Tools tab on the upper right side of the page to check the installation status. That's it!

## User stories:
Notes from WideFocus:

> I realize that most users will block most forms of tracking, but I still think this could be a valuble move in terms of conversion tracking and demographic information on LinkedIn. We're driving enough traffic that even if we only get 50% of users that would still give us some pretty cool insights. Here's a breakdown of what we might expect:
> 
> Installing LinkedIn Insight Tag allows you to:
> * Track Website Conversions: automatically optimize campaigns for more conversions and high-quality results.
> * Re-engage website visitors by retargeting them.
> * Unlock demographic insights about your website visitors: such as job titles, companies, industries, and more. (Once we hit 300 users.)
> * Track conversions from people who viewed your ad, not just who clicked.
> * Use automated bidding for higher conversions.
> * Set a conversion value: how much you deem each conversion is worth to you for the particular action.
> 
> Installing Twitter Insight Tag allows you to:
> * Measure your return on ad spend by tracking the actions people take after viewing or engaging with your ads on Twitter.
> * See conversions at campaign and tweet level as well as impressions, engagements, spend, and cost-per-action.
> * Retarget ads to people who recently visited your website.

## Acceptance criteria:
- [ ] Twitter code is installed on site and reporting
- [ ] LinkedIn code is installed on site and reporting

## Related links or issues:
https://www.linkedin.com/help/lms/answer/65521

## Feature Ready Checklist:

- [ ]  Defined with user stories
- [ ]  Defined with acceptance criteria
- [ ]  Dependencies identified

## Feature Done Checklist:

- [ ] Confirmed against acceptance criteria
- [ ] Builds without errors
- [ ] Deployed on test environment
- [ ] QA performed & issues resolved
