### ISSUE TITLE
4.1-UI-Q4-18: Do a performance review on the site & implement improvements to improve performance by 25%

### ISSUE THREAD

**Issue by dclear** [drud/ddevcom#87]
## Key Result Description

Do a performance review on the site and implement improvements to improve performance by 25%

## Acceptance Criteria

- [x] required issues stubbed and estimated
- [x] MVP issues added to this epic
- [x] Reviewed with team
