### ISSUE TITLE
4.2-UI-Q4-18: Install leading GDPR-compliant plugin

### ISSUE THREAD

**Issue by dclear** [drud/ddevcom#88]
## Key Result Description

Install leading GDPR-compliant plugin

## Acceptance Criteria

- [x] required issues stubbed and estimated
- [x] MVP issues added to this epic
- [x] Reviewed with team
