### ISSUE TITLE
4.3-UI-Q4-18: Implement and support product pages and initiatives from OSP

### ISSUE THREAD

**Issue by dclear** [drud/ddevcom#89]
## Key Result Description

Implement and support product pages and initiatives from OSP

## Acceptance Criteria

- [x] required issues stubbed and estimated
- [x] MVP issues added to this epic
- [ ] Reviewed with team
