### ISSUE TITLE
Update ddev.com site

### ISSUE THREAD

**Issue by ekl1773** [drud/ddevcom#92]
## Feature Description:
Top-Level Epic for IA, Wireframes, Implementation for an update of ddev.com

## Acceptance criteria:
All issues within epic are completed / closed.

## Related links or issues:
Initial sitemap doc here: https://docs.google.com/document/d/1Y4nGanLVV0vW5BM62usiKOyJRoEPQaL9GttK0UdEyfU/edit#

## Feature Ready Checklist:

- [ ]  Defined with user stories
- [x]  Defined with acceptance criteria
- [ ]  Dependencies identified

## Feature Done Checklist:

- [ ] Confirmed against acceptance criteria
- [ ] Builds without errors
- [ ] Deployed on test environment
- [ ] QA performed & issues resolved
